name: bulletin_app
description: Application Flutter pour la gestion des bulletins d'achat.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_riverpod: ^2.4.0
  hooks_riverpod: ^2.4.0
  flutter_hooks: ^0.21.3+1
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  drift: ^2.11.1
  sqlite3_flutter_libs: ^0.5.15
  path: ^1.8.3
  path_provider: ^2.0.15
  pdf: ^3.10.6
  printing: ^5.11.0
  collection: ^1.17.1
  flex_color_scheme: ^8.3.0
  uuid: ^4.5.1
  equatable: ^2.0.5
  http: ^1.1.0
  connectivity_plus: ^7.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  drift_dev: ^2.28.3
  mocktail: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/fonts/
    - packages/drift/web/worker.dart.js
    - packages/drift/web/worker.dart.js.map
    - packages/drift/web/wasm/sql-wasm.wasm
    - packages/drift/web/wasm/sql-wasm.js
  generate: true
