name: bulletin_app
description: Application Flutter pour la gestion des bulletins d'achat.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  flutter_riverpod: ^2.4.0
  hooks_riverpod: ^2.4.0
  flutter_hooks: ^0.18.6
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0
  drift: ^2.11.1
  drift_flutter: ^2.11.1
  sqlite3_flutter_libs: ^0.5.15
  path: ^1.8.3
  path_provider: ^2.0.15
  pdf: ^3.10.6
  printing: ^5.11.0
  collection: ^1.17.1
  flex_color_scheme: ^7.2.0
  uuid: ^3.0.7
  equatable: ^2.0.5
  http: ^1.1.0
  connectivity_plus: ^5.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  drift_dev: ^2.11.1
  mocktail: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/fonts/
  generate: true
